apiVersion: apps/v1
kind: Deployment
metadata:
  name: musical
  labels:
    app: musical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musical
  template:
    metadata:
      labels:
        app: musical
    spec:
      containers:
        - name: musical
          image: "gimewn/musical24:v1"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - mountPath: "/mnt/data"
              name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile 