name: Trigger Jenkins on Reservation Changes

on:
  push:
    paths:
      - 'reservation/**'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins
        run: |
          curl -X POST http://20.41.112.200:8080/github-webhook/
        env:
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
